# Generated by Django 4.2 on 2025-10-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание клиента'),
        ),
    ]
