# Generated by Django 4.2 on 2025-10-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_viewedrequest'),
        ('main', '0002_request_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.managerprofile', verbose_name='Менеджер'),
        ),
    ]
