# Generated by Django 4.2 on 2025-10-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_unique_together'),
        ('main', '0003_alter_request_responsible_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='crm.client', verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
