# Generated by Django 4.2 on 2025-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_notification_client_alter_request_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AlterField(
            model_name='project',
            name='object_type',
            field=models.CharField(choices=[('residential', 'Жилые комплексы'), ('commercial', 'Торговые центры и офисные здания'), ('social', 'Социально-значимые объекты'), ('other', 'Без категории')], default='other', max_length=50, verbose_name='Тип объекта'),
        ),
    ]
