# Generated by Django 4.2 on 2025-11-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_description_alter_project_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='request',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='request',
            name='pd_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='request',
            name='policy_version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Версия политики'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
