# Generated by Django 4.2 on 2025-10-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='request',
        ),
        migrations.AddField(
            model_name='comment',
            name='rrequest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crm_comments', to='main.request', verbose_name='Заявка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
