# Generated by Django 4.2 on 2025-10-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_comment_request_comment_rrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rrequest',
            new_name='request',
        ),
    ]
