# Generated by Django 4.2 on 2025-10-23 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_managerprofile_created_at_managerprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'request')},
            },
        ),
    ]
