# Generated by Django 4.2 on 2025-10-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_viewedrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя кандидата')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий кандидата')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки админа')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
