# Generated by Django 4.2 on 2025-10-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_client_company_name_alter_client_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company_name', 'phone')},
        ),
    ]
