# Generated by Django 4.2 on 2025-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_vacancy_options_vacancy_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(blank=True, help_text='Например: Полная занятость, удаленная работа', max_length=100, null=True, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, help_text='Например: от 1 года, без опыта', max_length=100, null=True, verbose_name='Опыт работы'),
        ),
    ]
