# Generated by Django 4.2 on 2025-11-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_vacancy_employment_type_vacancy_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение')),
                ('background_color', models.CharField(default='#1E3A8A', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет текста')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки')),
                ('button_color', models.CharField(default='#C9A96A', max_length=7, verbose_name='Цвет кнопки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания показа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промо-блок',
                'verbose_name_plural': 'Промо-блоки',
                'ordering': ['-created_at'],
            },
        ),
    ]
