# Generated by Django 4.2 on 2025-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_promoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoblock',
            name='background_gradient',
            field=models.BooleanField(default=False, verbose_name='Градиентный фон'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='background_overlay',
            field=models.BooleanField(default=False, verbose_name='Наложение на фон'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='background_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='Прозрачность наложения'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='block_height',
            field=models.PositiveIntegerField(default=300, verbose_name='Высота блока'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='block_width',
            field=models.CharField(default='100%', max_length=20, verbose_name='Ширина блока'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='border_radius',
            field=models.PositiveIntegerField(default=12, verbose_name='Скругление углов'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='button_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='Размер шрифта кнопки'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет текста кнопки'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='content_position',
            field=models.CharField(default='center', max_length=20, verbose_name='Позиция контента'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='custom_font_url',
            field=models.URLField(blank=True, verbose_name='URL кастомного шрифта'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter'), ('roboto', 'Roboto'), ('opensans', 'Open Sans'), ('montserrat', 'Montserrat'), ('playfair', 'Playfair Display'), ('lora', 'Lora'), ('raleway', 'Raleway'), ('ubuntu', 'Ubuntu')], default='inter', max_length=20, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='gradient_angle',
            field=models.IntegerField(default=135, verbose_name='Угол градиента'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='gradient_end',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Конец градиента'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='gradient_start',
            field=models.CharField(default='#1E3A8A', max_length=7, verbose_name='Начало градиента'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='layout',
            field=models.CharField(choices=[('text_left', 'Текст слева, изображение справа'), ('text_right', 'Текст справа, изображение слева'), ('text_top', 'Текст сверху, изображение снизу'), ('text_bottom', 'Текст снизу, изображение сверху'), ('text_overlay', 'Текст поверх изображения'), ('text_only', 'Только текст'), ('image_only', 'Только изображение')], default='text_left', max_length=20, verbose_name='Макет'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет наложения'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='padding_bottom',
            field=models.PositiveIntegerField(default=40, verbose_name='Отступ снизу'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='padding_left',
            field=models.PositiveIntegerField(default=40, verbose_name='Отступ слева'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='padding_right',
            field=models.PositiveIntegerField(default=40, verbose_name='Отступ справа'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='padding_top',
            field=models.PositiveIntegerField(default=40, verbose_name='Отступ сверху'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='shadow_effect',
            field=models.BooleanField(default=False, verbose_name='Тень'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='text_align',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='left', max_length=10, verbose_name='Выравнивание текста'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='text_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='Размер шрифта текста'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='title_font_size',
            field=models.PositiveIntegerField(default=24, verbose_name='Размер шрифта заголовка'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='use_image_as_background',
            field=models.BooleanField(default=False, verbose_name='Использовать изображение как фон'),
        ),
        migrations.AddField(
            model_name='promoblock',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL видео'),
        ),
    ]
