# Generated by Django 4.2 on 2025-11-25 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_promoblock_background_gradient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='pd_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pd_agreed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата согласия на обработку ПД'),
            preserve_default=False,
        ),
    ]
