# Generated by Django 4.2 on 2025-11-26 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_add_pd_fields_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pd_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pd_agreed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата согласия на обработку ПД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='policy_version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Версия политики'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
