# Generated by Django 4.2 on 2026-06-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_feedback_ip_address_feedback_pd_agreed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', '🆕 Новая заявка'), ('request_assigned', '👤 Назначение заявки'), ('status_changed', '🔄 Изменение статуса'), ('new_comment', '💬 Новый комментарий'), ('new_feedback', '📨 Новое сообщение'), ('new_candidate', '🎯 Новый кандидат'), ('system', '⚙️ Системное уведомление')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.managerprofile', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Внутреннее уведомление',
                'verbose_name_plural': 'Внутренние уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='internalnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='crm_interna_recipie_892799_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnotification',
            index=models.Index(fields=['created_at'], name='crm_interna_created_c42bb5_idx'),
        ),
    ]
